version: "3.7"
services:
  rabbitmq_management:
    image: rabbitmq:management-alpine
    ports:
      - "8080:15672"
      - "5672:5672"
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=@bc123